version: '3.8'

services:
  wikilive_pg:
    image: postgres:latest
    container_name: wikilive_pg
    environment:
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: wikievents
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - superset-net

  superset:
    image: apache/superset:latest
    container_name: superset_app
    environment:
      SUPERSET_SECRET_KEY: 'your_secret_key_here'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_FIRSTNAME: Superset
      ADMIN_LASTNAME: Admin
      ADMIN_EMAIL: admin@superset.com
    ports:
      - "8088:8088"
    depends_on:
      - wikilive_pg
    networks:
      - superset-net
volumes:
  pgdata:

networks:
  superset-net:
